### PR TITLE
rename borderWidth to cborderWidth

### PR DESCRIPTION
**Pull request by Bernix01**
This library does what it says. But I have found a little collateral... 
The property borderWidth clashes with swiftutilities. 

It's pretty difficult to handle this without changing the dependency code.

### CODE REVIEW

**Comment by BeauNouvelle** [comment]
Thanks for this. How does `checkboxBorderWidth` sound?

**Comment by BeauNouvelle** [comment]
Which SwiftUtilities project were you referring to?

**Comment by Bernix01** [comment]
my bad, it is [swifterswift](https://github.com/SwifterSwift/SwifterSwift/blob/42b95995cff591644d3c385f02edc1305e77a0ac/Sources/SwifterSwift/UIKit/UIViewExtensions.swift#L82)

**Comment by BeauNouvelle** [comment]
I've renamed it to `borderLineWidth`.

**Pull request closed without merging**
